cofferup/urls.py
from django.contrib import admin
from django.urls import include, path
from cofferupApp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cofferupApp.urls')),
]

cofferupApp/urls.py
from django.urls import include,path
from .views import *
from .models import *

app_name = "cofferupApp"

urlpatterns = [
    path('home', contribution_list, name='home'),
    path('', about, name='about'),
    path('coffers/mycoffers/', my_coffers_list, name='my_coffers'),
    path('coffers', coffers_list, name = 'coffers'),
    path('profile', user_detail, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout', logout_user, name='logout'),
    path('coffers/form', coffer_form, name='coffer_form'),
    path('profile/form', profile_form, name='profile_form'),
    path('coffers/<int:coffer_id>', coffer_detail, name='coffer'),
    path('coffers/mysettledcoffers', my_settled_coffers_list, name = 'my_settled_coffers'),
    path('coffers/mysettledcoffers/<int:coffer_id>', my_settled_coffers_list, name='my_settled_coffers'),
    path('coffers/mycoffers/<int:coffer_id>', my_coffers_list, name='my_coffers'),
    path('coffers/mycoffers/contribution/<int:coffer_id>', contribution_list, name='contribution_list'),
    path('register', user_register, name='user_register'),
]

cofferupApp/models/coffer.py
# from django.db import models
from django.db.models import F
# from cofferupApp.models import Organization
from .contributor import Contributor
from django.db import models


class Coffer(models.Model):

    # organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    admin = models.ForeignKey(Contributor, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    date_start = models.DateField(auto_now=False, auto_now_add=False)
    date_end = models.DateField(auto_now=False, auto_now_add=False)
    description = models.CharField(max_length=255, null=True)

    # class Meta:
    #     ordering = (F('organization.name').asc(nulls_last=True),)

cofferupApp/models/contributor.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# from cloudinary.models import CloudinaryField

class Contributor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image_url = models.URLField(default="", max_length=200)

    # def __str__(self):
    #     return f'{self.user.first_name} {self.user.last_name}'

    # class Meta:
    #     ordering = (F('user.date_joined').asc(nulls_last=True),)

# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property

    @receiver(post_save, sender=User)
    def create_contributor(sender, instance, created, **kwargs):
        if created:
            Contributor.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.

    @receiver(post_save, sender=User)
    def save_contributor(sender, instance, **kwargs):
        instance.contributor.save()

cofferupApp/models/contributor_coffer.py
from django.db import models
from django.db.models import F
from .contributor import Contributor
from .coffer import Coffer

class ContributorCoffer(models.Model):

    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    coffer = models.ForeignKey(Coffer, on_delete=models.CASCADE)
    is_settled=models.BooleanField(default=0)
    # is_open=models.BooleanField(default=True)

    # def __str__(self):
    #     return f'{self.user.first_name} {self.user.last_name}'

    # class Meta:
    #     ordering = (F('user.date_joined').asc(nulls_last=True),)

cofferupApp/models/contributor_coffer_transaction.py
from django.db import models
from django.db.models import F
from .contributor_coffer import ContributorCoffer


class ContributorCofferTransaction(models.Model):

    contributor_coffer=models.ForeignKey(ContributorCoffer, on_delete=models.CASCADE)
    description=models.CharField(max_length=255)
    amount=models.IntegerField()
    transaction_date=models.DateTimeField(auto_now=False, auto_now_add=True)

    # def __str__(self):
    #     return f'{self.user.first_name} {self.user.last_name}'

    # class Meta:
    #     ordering = (F('user.date_joined').asc(nulls_last=True),)

cofferupApp/models/organization.py
# from django.db import models
# from django.db.models import F


# class Organization(models.Model):

#     name = models.CharField(max_length=50)
#     description = models.CharField(max_length=255)
#     date_created = models.DateTimeField(auto_now=False, auto_now_add=True)

#     class Meta:
#         ordering = (F('name').asc(nulls_last=True),)

cofferupApp/models/organization_contributor.py
# from django.db import models
# from django.db.models import F
# from cofferupApp.models import Contributor, Organization

# class OrganizationContributor(models.Model):

#     contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
#     organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    # def __str__(self):
    #     return f'{self.user.first_name} {self.user.last_name}'

    # class Meta:
    #     ordering = (F('user.date_joined').asc(nulls_last=True),)

cofferupApp/views/about.py
from django.shortcuts import render

def about(request):
    if request.method == 'GET':
        template = 'about.html'
        context = {}

        return render(request, template, context)

cofferupApp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

cofferupApp/templates/about.html
{% extends 'shared/base.html' %}

{% load static %}


{% block content %}

<img class="welcome-logo" src="https://res.cloudinary.com/anymouse/image/upload/v1584581330/CofferUp/CoffErUp-logos_black_zmnxcy.png" alt="CofferUp Logo">
<div class="welcome-text">
    <p>Coff'ErUp is a place where you can create and maintain digital collection coffers.</p>
    <p>There are several types of coffers:</p>
    <ul>
        <li> Open Coffers - Coffers that have already started and are accepting contributions/penalties
        <li> Future Coffers - Coffers that have been created but the start date has not arrived
        <li> Closed Coffers - Coffers whose end date has passed
        <ul>
            <li> Settled - Closed Coffers that have been Paid
            <li> Unsettled - Closed Coffers that are Unpaid
        </ul>
    </ul>
    <p>Multiple users can contribute to multiple coffers.</p>
    <p>So get started and join your friends in filling the coffers.</p>


</div>


{% endblock %}


2

cofferupApp/templates/coffers/detail.html
{% extends 'shared/base.html' %}


{% load static %}


{% block content %}

<div class="welcome-text">
    <h1>{{coffer.name}}</h1> 
    <p>open date: {{coffer.date_start}}</p>
    <p>close date: {{coffer.date_end}}</p>
    <p>{{coffer.description}}</p>

    <h2>balance: {{coffer.sum}}</h2>

    {% for line in coffer.contributor_sums %}
    <h3><span id="transaction-image"><img src="{{line.image_url}}" id="transaction-image" alt="me"></span> {{line.first_name}} {{line.last_name}}     {{line.total}}</h3>
    {% endfor %}

    <div>
    <h2>all transactions</h2>
    {% for line in coffer.contributions %}
        <div class="flexRow">
            <p class="xact-detail-image">
                <img src="{{line.contributor_coffer.contributor.image_url}}" id="transaction-image" alt="me">
            </p>
            <p class="xact-detail-date">
                {{line.transaction_date}}
            </p>
            <p class="xact-detail-name">
                {{line.contributor_coffer.contributor.user.first_name}} {{line.contributor_coffer.contributor.user.last_name}} 
            </p>
            <p class="xact-detail-amount">
                {{line.amount}}
            </p>
            <p class="xact-detail-description">
                {{line.description}}
            </p>
        </div>
    {% endfor %}

    {% comment %} put last 10 transactions here {% endcomment %}
</div>

{% endblock %}

cofferupApp/templates/coffers/form.html
{% extends 'shared/base.html' %}

{% load static %}

    {% block content %}
    <div class="form-text">
    <h2>new coffer details</h2>
    <br />
        <form action="{% url 'cofferupApp:coffers' %}" method='post'>
        {% csrf_token %}
            <fieldset class="form-group">
                <label for="name">coffer name: </label>
                <input class="form-control" id="name" type="text" name="name">
            </fieldset>
            <fieldset class="form-group">
                <label for="description">description: </label>
                <input class="form-control" id="description" type="text" name="description">
            </fieldset>
            <fieldset class="form-group">
                <label for="date_start">coffer open date: </label>
                <input class="form-control" id="date_start" type="date" name="date_start">
            </fieldset>
            <fieldset class="form-group">
                <label for="date_end">coffer close date: </label>
                <input class="form-control" id="date_end" type="date" name="date_end">
            </fieldset>
            <br />
            <button class="btn button-add" type="submit">+ new coffer</button>
        </form>
        </div>
    {% endblock %}

cofferupApp/templates/coffers/list.html
{% extends 'shared/base.html' %}

{% load static %}

{% block content %}

<div class="list-text">
    <button class="btn btn-lg create-button"><a href="{% url 'cofferupApp:coffer_form' %}">create new coffer</a></button>

    <h1>join a coffer</h1>

        <div class="flexCol">
        {% for coffer in all_coffers %}
            <div>
                <a href = {% url 'cofferupApp:coffer' coffer.id %}>
                <span class="div-name"><h3>{{coffer.name}}</h3></span></a> 
                ({{coffer.description}})
                <p>will close {{coffer.date_end}}</p>
                
                <form action="{% url 'cofferupApp:my_coffers' coffer.id %}" method="post">
                {% csrf_token %}
                <button class="btn button-add" type="submit">+ my coffers</button>
                </form>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

cofferupApp/templates/coffers/my_list.html
{% extends 'shared/base.html' %}

{% load static %}

    {% block content %}
    <div class="list-text">
        <h1>my open coffers</h1>

        <div class="flexCol">
        {% for coffer in my_open_coffers %}

            <a href = {% url 'cofferupApp:coffer' coffer.coffer.id %}>
            <span class="div-name"><h3>{{coffer.coffer.name}}</h3></span></a> 
            <div class="flexRow">
                <div class="inner-div">   
                    ({{coffer.coffer.description}})
                    <p>will close {{coffer.coffer.date_end}}</p>
                    <form action="{% url 'cofferupApp:my_coffers' coffer.coffer.id %}" method="POST">
                    <input type="hidden" name="actual_method" value="DELETE">
                    {% csrf_token %}

                    <button class="btn" type="submit">- my coffers</button>
                    </form>
                </div>
                <div class="inner-div-2">
            <form action="{% url 'cofferupApp:contribution_list' coffer.id %}" method='post'>
            {% csrf_token %}
                <fieldset>
                    <label for="amount">amount (cents): </label>
                    <input id="amount" type="number" step="25" name="amount">
                </fieldset>
                <fieldset>
                    <label for="description">description: </label>
                    <input id="description" type="text" name="description">
                </fieldset>
                <button class="btn" type="submit">+ contribution</button>
            </form>
        <script>
                alert(message)
        </script>


                </div>
            </div>

        {% endfor %}
        </div> 

        <h1>my future coffers</h1>        
        <div class="flexCol">
        {% for coffer in my_future_coffers %}
            <div>
            <a href = {% url 'cofferupApp:coffer' coffer.coffer.id %}>
           <span class="div-name"><h3>{{coffer.coffer.name}}</h3></span></a> 
            ({{coffer.coffer.description}})
            <p>will close {{coffer.coffer.date_end}}</p>
            <form action="{% url 'cofferupApp:my_coffers' coffer.coffer.id %}" method="POST">
            <input type="hidden" name="actual_method" value="DELETE">
            {% csrf_token %}

            <button class="btn" type="submit">- my coffers</button>
            </form>
            </div>
        {% endfor %}
        </div> 

        <h1>my closed coffers</h1>        
        <div class-"flexCol">
        {% for coffer in my_closed_coffers %}
            <div>
            <a href = {% url 'cofferupApp:coffer' coffer.coffer.id %}>
           <span class="div-name"><h3>{{coffer.coffer.name}}</h3></span></a> 
            ({{coffer.coffer.description}})
            <p>will close {{coffer.coffer.date_end}}</p>
            
            {% comment %} <form action="{% url 'cofferupApp:my_coffers' coffer.coffer.id %}" method="POST">
            <input type="hidden" name="actual_method" value="DELETE">
            {% csrf_token %}

            <button class="btn" type="submit">- my coffers</button>
            </form> {% endcomment %}

            <form action="{% url 'cofferupApp:my_settled_coffers' coffer.id %}" method="POST">
            <input type="hidden" name="actual_method" value="PATCH">
            {% csrf_token %}

            <button class="btn" type="submit">$ coffer</button>
            </form>

            </div>
        {% endfor %}
        </div>
    </div>
    {% endblock %}

cofferupApp/templates/coffers/my_paid_list.html
{% extends 'shared/base.html' %}

{% load static %}

{% block content %}
<div class="list-text">
    <h1>my settled coffers</h1>
    <div>
    {% for coffer in my_coffers %}
        <div>
        <a href = {% url 'cofferupApp:coffer' coffer.coffer.id %}>
        <span class="div-name"><h3>{{coffer.coffer.name}}</h3></span></a> 
        ({{coffer.coffer.description}})
        <p>closed {{coffer.coffer.date_end}}</p>

        </div>
    {% endfor %}
    </div> 
</div>
{% endblock %}

cofferupApp/templates/home.html
{% extends 'shared/base.html' %}

{% load static %}


{% block content %}

<div class="detail-text"> 
    <h2>Have you been naughty or nice?!</h2>

    <h3>Your last 10 contributions</h3>
    <br />

    {% for c in my_contribs%}

        <div class="flexRow">
            <p class="xact-detail-date">
                {{c.transaction_date}}
            </p>
            <p class="xact-detail-name">
                {{c.contributor_coffer.coffer.name}}
            </p>
            <p class="xact-detail-amount">
                {{c.amount}}
            </p>
            <spa class="xact-detail-description">
                {{c.description}}
            </p>
        </div>

    {% endfor %}

</div>

{% comment %} <img class="welcome-logo" src="https://res.cloudinary.com/anymouse/image/upload/v1584581330/CofferUp/CoffErUp-logos_black_zmnxcy.png" alt="CofferUp Logo">
<div class="welcome-text">
    <p>Coff'ErUp is a place where you can create and maintain digital collection coffers.</p>
    <p>There are several types of coffers:</p>
    <ul>
        <li> Open Coffers - Coffers that have already started and are accepting contributions/penalties
        <li> Future Coffers - Coffers that have been created but the start date has not arrived
        <li> Closed Coffers - Coffers whose end date has passed
        <ul>
            <li> Settled - Closed Coffers that have been Paid
            <li> Unsettled - Closed Coffers that are Unpaid
        </ul>
    </ul>
    <p>Multiple users can contribute to multiple coffers.</p>
    <p>So get started and join your friends in filling the coffers.</p> {% endcomment %}


</div>


{% endblock %}


2

cofferupApp/templates/profile/detail.html
{% extends 'shared/base.html' %}

{% load static %}

{% block content %}
<div class="list-text">

    <h1>my profile</h1>
        <br />
        <p><img id="profile-image" src="{{profile.image_url}}"></b></p>
        <p>name: <b>{{user.first_name}} {{user.last_name}}</b></p>
        <p>username: <b>{{user.username}}</b></p>
        <p>e-mail: <b>{{user.email}}</b></p>
        <br />

    <form action="{% url 'cofferupApp:profile_form' %}" method="GET">
        {% csrf_token %}
        <button class="btn">Edit</button>
    </form>
</div>
{% endblock %}

cofferupApp/templates/profile/form.html
{% extends 'shared/base.html' %}

{% load static %}

{% block content %}
<div class="form-text">
    <h1>my profile</h1>
    <br />
    {% comment %} <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.avatar }}
        <input type="submit" value="Upload avatar">
    </form> {% endcomment %}

    <form action="{% url 'cofferupApp:profile'  %}" method='POST' >
    <input type="hidden" name="actual_method" value="PATCH">
    {% csrf_token %}

        <fieldset class="form-group">
            <label for="image_url">image url: </label>
            <input class="form-control" id="image_url" type="url" name="image_url" value="{{contributor.image_url}}"}>
        </fieldset>
        <fieldset class="form-group">
            <label for="first_name">first name: </label>
            <input class="form-control" id="first_name" type="text" name="first_name" value={{user.first_name}}>
        </fieldset>
        <fieldset class="form-group">
            <label for="last_name">last name: </label>
            <input class="form-control" id="last_name" type="text" name="last_name" value={{user.last_name}}>
        </fieldset>
        <fieldset class="form-group">
            <label for="username">username: </label>
            <input class="form-control"  id="username" type="text" name="username" value={{user.username}}>
        </fieldset>
        <fieldset class="form-group">
            <label for="email">email: </label>
            <input class="form-control" id="email" type="text" name="email" value={{user.email}}>
        </fieldset>
        <br />
        <button class="btn" type="submit">Submit Changes</button>
    </form>
</div>
{% endblock %}

cofferupApp/templates/shared/base.html
{% load static %}

<!DOCTYPE html>
<html>

    <head>
        <link rel="icon" type="image/png" href="https://res.cloudinary.com/anymouse/image/upload/v1584581292/CofferUp/Coff_ErUp-logos_transparent_zslip8.png">
        <title>CofferUp</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'home.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Itim&display=swap" rel="stylesheet">

    </head>

    <body>
    {% comment %} <img src="https://res.cloudinary.com/anymouse/image/upload/v1584581330/CofferUp/CoffErUp-logos_black_zmnxcy.png" alt="CofferUp Logo"> {% endcomment %}
        {% if user.is_authenticated %}
            <nav id ="site-nav">
                <ul class="navList">
                    <li class="navList__route"><a href="{% url 'cofferupApp:home' %}"><img class="nav-bar-logo" src="https://res.cloudinary.com/anymouse/image/upload/v1584581286/CofferUp/Coff_ErUp-logos_black_esz9zx.png" alt="home"></a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:my_coffers' %}">my coffers</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:coffers'%}">join a coffer</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:my_settled_coffers'%}">settled coffers</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:profile'%}">my profile</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:about'%}">about</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:logout'%}">logout</a></li>
                </ul>
            </nav>
        
        {% else %}
            <nav id ="site-nav">
                <ul class="navList">
                    <li class="navList__route"><a href="{% url 'cofferupApp:about' %}"><img class="nav-bar-logo" src="https://res.cloudinary.com/anymouse/image/upload/v1584581330/CofferUp/CoffErUp-logos_black_zmnxcy.png" alt="about"></a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:login'%}">login</a></li>
                    <li class="navList__route"><a href="{% url 'cofferupApp:user_register'%}">register</a></li>
                </ul>
            </nav>
        
        {% endif %}

        <main class="main-content">
            {% block content %}
            {% endblock %}
        </main>

        {% block scripts %}
        {% endblock scripts %}

    </body>
</html>